### ISSUE TITLE
Merge basic client support

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#171]
@jimmyt857 has been adding client support. This should be merged in some way.

**Comment by alexhultman** [comment]
I'm thinking you abstract out the event-loop from the Server and into its own class. This way you can share multiple Servers and Clients on the same event-loop in a clear way. You want to be able to run clients and servers on the same thread:

EventSystem es;

Server s1(es, 3000);
Server s2(es, 3001);

es.run();

and

EventSystem es;

Client c1(es);
Server s1(es, 3000);

es.run();

**Comment by alexhultman** [comment]
https://github.com/jimmyt857/uWebSockets/tree/client_integration

**Comment by jimmyt857** [comment]
Sure; that looks great. Just to be clear, that's my old client branch, I should probably delete it. The newer branch is https://github.com/uWebSockets/uWebSockets/tree/client.

There is another design decision needing to be made with regards to the options and the URL the client connects to. Currently, you call `client.Connect(url)` to connect, meaning that you can have 1 client object with connections to many different urls. However, this is a bit odd because there is only 1 set of options shared between the connections, so in reality the connections you can make are restricted based on which ssl certificates / permessage deflate options you pick. I see 3 potential resolutions:

- Each connection stores its own options; Obviously this is a bad idea for us, but it is an option.
- Shared url as an option: This makes the interface very clear; a Client allows you to create 1 or more connections to a single endpoint. However, this loses some convenience, especially since I think most client users won't care about having different options for each connection.
- Add the url as a parameter to OnConnection: This is my favorite option, as it keeps the flexibility and lets the user decide if they need to store the url - connection mapping. The interface becomes a little bit more complex.

**Comment by alexhultman** [comment]
Sure but you could create multiple ClientGroups (I think thats a better name for Client) and create connections from the group with wanted settings.

**Comment by jimmyt857** [comment]
So it sounds like the third option with a renaming of Client --> ClientGroup will work? With that change, a ClientGroup represents a set of connections to (possibly) multiple urls, sharing a set of parameters.

**Comment by alexhultman** [comment]
Yeah I think that is a decent initial interface. Things will iterate with time but I think it will do for a first version.

**Comment by erichocean** [comment]
I'm definitely interested in being able to use µWebSockets to run multiple socket servers on the same run loop, and right now, I'm handling the lack of client support with a simple Node.js WebSocket proxy. Would love to see both.

BTW Using it from C++, not Node.js. Thanks for open sourcing/building it!!!

**Comment by jimmyt857** [comment]
You can already do the first part (multiple servers on one loop). The UI just isn't obvious. Just do something like this:

```c++
Server s1 ( ... );
Server s2 ( ... );
s1.run(); // or s2.run()

**Comment by socmag** [comment]
Hey, how is it going with client support?  Hoping to use it soon.

**Comment by jimmyt857** [comment]
If you don't need ssl or permessage deflate, there is an outdated branch you can use where it is completed finished: https://github.com/uWebSockets/uWebSockets/tree/client

**Comment by jimmyt857** [comment]
I should add that the interface will most likely be slightly different when it is introduced to the main branch.
