### ISSUE TITLE
Testing wanted: Windows support

### ISSUE THREAD

**Issue by alexhultman** [uWebSockets/uWebSockets#186]
0.7.3 comes with pre-compiled binaries for Windows x64 for Node.js 6.3.0. It does not support SSL (SSL will be supported in Node.js 6.4.x).

`npm install uws` should work. There might be some initial hickups though. Please write your report here, include Windows version and Node.js version (6.3.0 only supported).

**Comment by efkan** [comment]
I've applied a simple test for Windows support.

* I updated my Node.js to `v6.3.0`. 

* I installed `uws`

* I added the following code as directed the guide: 

```
io.engine.ws = new (require('uws').Server)({
    noServer: true,
    clientTracking: false,
    perMessageDeflate: false
});
```
* I added the following code to my `app.js` file and some code to the client's `JS` file:

```
io.on('connection', function (socket) {
	console.log('user connected')
	setTimeout(function () {socket.emit('news', { data: 'hello world' }) }, 1000)
	socket.on('client to server', function(message){
		console.log('client says: ', message.data)
	})
	socket.on('disconnect', function () {
		console.log('user disconnect')
	})
})
```

### Results:
I got the results below and _it seems working_:

```
user connected
client says:  Hey you server! You`ve said hello world to me...
```

Also I guess the issue was related with https://github.com/uWebSockets/uWebSockets/issues/162
