### ISSUE TITLE
Document thread safety

### ISSUE THREAD

**Issue by jackc** [uWebSockets/uWebSockets#244]
I'm trying to work in C++. There is an example of a multithreaded echo server, but that never sends to a socket on another worker/server. Is it safe to call `broadcast` from one server thread to another?

**Comment by alexhultman** [comment]
The threading model is a bit busted and needs some work but yes, the idea is that if you pass WORKER to the EventSystem constructor, all sockets that are created from this Server that makes use of this EventSystem is safe to use from any other thread (at least sending). It is safe to use, but there is no guarantee that there will be no race condition if you are broadcasting using the same Server from two different threads at the same time.

Race condition is up to solve by the user, and you can attach your own mutex to any WebSocket via setData, or have on mutex for one entire Server.

**Comment by agauniyal** [comment]
Is there any change regarding threading model with 0.10 as well? or the above explanation is sufficient for it.

**Comment by socmag** [comment]
My current implementation has a per client lock immediately before the call
to send(),  since I make heavy use of the pattern you are describing.

That is not perfect, but I was in a rush to port to 0.10.x and needed to
guarantee stability.

I have a plan for eliminating that lock,  although the granularity of those
locks seem fine in production code for now.

Alex has a plan as well, although there are some optimizations that can be
better done at a higher level if you really understand your own flows

I really would like to see BoringSSL integrated into master. I think that
would also help a lot, but for now it is just fine.

**Comment by alexhultman** [comment]
With 0.10.0 the threading model is the same but you need to opt-in to threading by calling Group::addAsync(). Why this strange name? Well, it is kind of messed up but by adding an async (uv_async_t) you make the Hub capable of listening for connection transfers. You transfer a connection between groups with ws.transfer(group). This way you get to transfer connections between CPU cores ay any time. You no longer have the restriction of only transfering connections at onUpgrade. This makes it possible to use uS::REUSE_PORT as a flag when listening so that the Linux kernel will load balance your connections and then you get to even them out if you want to (for instance, you can have a timer go off every 1 hours and evenly distribute the connections over all CPU cores).

**Comment by alexhultman** [comment]
I will be writing a user manual at some point. It's really over due.

**Comment by alexhultman** [comment]
Yeah, only Node.js is tied to OpenSSL. Any C++ only solution can use other SSL's like wolfSSL and such if we integrate them. Should be simple enough. I'm all for that support.

**Comment by socmag** [comment]
Yes and there is that, which is very cool but it does take some effort to
make use of properly.

On Oct 6, 2016 8:19 PM, "Alex Hultman" <notifications@github.com> wrote:

With 0.10.0 the threading model is the same but you need to opt-in to
threading by calling Group::addAsync(). Why this strange name? Well, it is
kind of messed up but by adding an async (uv_async_t) you make the Hub
capable of listening for connection transfers. You transfer a connection
between groups with ws.transfer(group). This way you get to transfer
connections between CPU cores ay any time. You no longer have the
restriction of only transfering connections at onUpgrade. This makes it
possible to use uS::REUSE_PORT as a flag when listening so that the Linux
kernel will load balance your connections and then you get to even them out
if you want to (for instance, you can have a timer go off every 1 hours and
evenly distribute the connections over all CPU cores).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/uWebSockets/uWebSockets/issues/244#issuecomment-252045961>,
or mute the thread

**Comment by socmag** [comment]
I am using the reuse port stuff,  and it is really awesome

**Comment by alexhultman** [comment]
Group::addAsync should be renamed to something like Group::listen(ASYNC); Where ASYNC is some negative number to differ it from port.

**Comment by alexhultman** [comment]
ASYNC should be renamed to TRANSFERS. The concept is that you listen to a transfer instead of a port.

**Comment by gongzhxu** [comment]
if not provide thread safe, how can i use

**Comment by alexhultman** [comment]
If you need absolute thread safety you need to attach a mutex to your socket with setData and lock/unlock it before/after any use of the socket. You can get the sockets mutex with getData.

**Comment by lucasterra** [comment]
@alexhultman, what's the threading model used in the [default example](https://github.com/uWebSockets/uWebSockets#c)? Is it safe to assume it uses one single thread for sending, receiving, connecting, etc?

**Comment by alexhultman** [comment]
Yes it will only use 1 thread unless you create more. 1 Hub per thread.

**Comment by lucasterra** [comment]
Thank you.

**Comment by mafrost** [comment]
I've been playing around with this library some (in C++) and have some questions about thread safety in the latest version and have not been able to find an answer in the existing issues.

I need to run the websocket server in a separate thread to be able to handle other types of requests, such as udp receives, http requests, etc.

So given the following scenario: (pseudo)

```
this->hub.onConnection... // handle a new client, store it in a thread safe list
this->hub.onDisconnection... // remove it safely from the list
this->hub.onMessage... // add to a thread safe message queue

this->webSocketServerThread = std::thread([this] () { 
    this->hub.run(); // my uwebsocket hub instance
});

this->receiveOtherTypeOfMessage(message) {
    // safely, for every client, send message
   for client in clients
       client.ws.send(message); // is this safe?
}
```

I want to send messages to all the clients in my thread safe list from main thread. Can this be done safely? 
I will not send to a client or close a connection based on an event from the uwebsocket thread. I will only send from the main thread.
What happens if I try to send data to a client during an internal uwebsocket "websocket termination" or similar? For earlier versions of the lib, you mention that it's possible using libuv. But after the major rewrite it seems it works differently.

I hope you can give some hints on how this could be done. 

PS. You've done a great job building this 👍 DS

**Comment by alexhultman** [comment]
as long as you lock before you remove the socket from your list, and also lock before you traverse the list you should be fine. you also need to call Group::addAsync to groups you want to control from different threads

**Comment by alexhultman** [comment]
There is now initial thread-safety in place that should document the problem better (You lock the Node which also documents the potential performance loss - you don't want to lock Nodes from different threads all the time so use transfer to group things where you need them). I'm closing this, future versions will have very clear documentation of what is thread safe or not. There is a macro THREADSAFE_FUNCTION in all functions that are thread safe (nice documentation).
