### ISSUE TITLE
Use Nan to abstract v8

### ISSUE THREAD

**Issue by Rush** [uWebSockets/uWebSockets#250]
I noticed that addon code is not using Nan https://github.com/nodejs/nan

When a new Node.js version is released there is a high chance things will break.

**Comment by alexhultman** [comment]
This project will never use NaN. When Google break V8 they break it for a reason and that is because they have to. By using NaN you disqualify yourself from this breakage and end up using some wrapped up ancient interface that Node.js devs have decided on. The fact that a swap from Buffer (Node.js) to ArrayBuffer (pure V8) almost doubled throughput by itself is enough to stay away from anything Node.js specific. Anyways, thanks for interest.

**Comment by Rush** [comment]
@alexhultman thanks for the explanation
