### ISSUE TITLE
Compatibility with Primus

### ISSUE THREAD

**Issue by stormwin** [uWebSockets/uWebSockets#275]
https://github.com/primus/primus/issues/498

@lpinca, @alexhultman Guys, there are lots of users and products that uses uws and primus. I am one of them, on multiple private products. 
Don't arguing and banning each other. Otherwise, you will loose your repos  'clients'

**Comment by alexhultman** [comment]
Sure, but the Primus camp is very strict about their way of doing things. They add a lot of overhead by copying buffers that are supposed to be zero-copy, they add full versions of EventEmitter and other stuff they call "the Spark", they have full blown versions of upgradeReq, even though that object holds references to closed net.Sockets that are just eager to get collected by the GC, essentially destroying the entire purpose of uws.

On top of this, both maintainers are extremely hostile to the uws project in general and do not share the vision of this project. They also complain about the scalability and performance - which is kind of a joke given how they mistreat uws inside of Primus.

They refuse to use the official interface, and instead rely on the low-level interface that is changing from time to time. This is not a good way of interfacing the uws module given that Primus does not enforce any particular version of uws and will thus continue to break from time to time.

If you are using the native low-level interface of uws, you better make sure to enforce a particular version of uws. Otherwise, the low-level interface should not be used.

But yes, the goal is to keep compatibility with Primus. You can still use v0.9.0 with Primus until this gets fixed.

**Comment by alexhultman** [comment]
@lpinca 
> If you are using Node.js and you think that the EventEmitter is wrong you should start looking somewhere else as basically everything in Node.js is built on top of the EventEmitter.

I'm not allowed to criticize Node.js? If EventEmitter is such a perfect entity, why do you personally maintain the project "eventemitter3"? Seems kind of hypocritical to me. You are allowed to reimplement the EventEmitter interface, but not me?

> The JS interface of uws is a mess.

The fact that you can pass the entire Primus test suite by simply taking the existing `ws` transformer and changing require('ws') to require('uws') is kind of arguing against that claim.

Not to mention the users of SocketCluster which seem pretty happy with the interface.
