### ISSUE TITLE
Output build log of node module on stdout

### ISSUE THREAD

**Issue by silverwind** [uWebSockets/uWebSockets#284]
I think it'd be more convenient to have the build log visible while building, as opposed to having to go digging for `build_log` every time it fails. What do you think?

**Comment by alexhultman** [comment]
So the idea with the deployment is to be Apple-esque. I want `npm install uws` to be as simple as it possibly can. That's why I'm putting so much focus on pre-building the lib for all three platforms to allow a seamless fallback (for most systems).

That's also why I'm not displaying the build log, or any details of errors. Because it doesn't really matter what the error is, it should just work out of the box anyways. If we display a wall of text filled with `ERROR: 0x2561788711` the average Noder will just leave and never try the lib again.

It makes no sense to display a wall of text of a failed build, when the pre-built binary runs just fine. That's why any error is delayed until the user tried to require the module inside of Node.js. Only if that fails (the build process has failed AND the pre-built binary is not compatible with the system) do we display an error, and that error is very simple for the user to understand:

`Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.`

I also get the feeling that most Node.js people absolutely hate C++ more than anything else on earth. They simply do not want to deal with it in any possible way. So it just needs to work.

**Comment by SEAPUNK** [comment]
By the way, is there any reason for the build step to run, if there are already prebuilt binaries in the package? Is it for building for the environments that don't have a prebuilt binary, or..?

**Comment by alexhultman** [comment]
There's not really any reason, it was recommended by @kapouer (he wrote the binding.gyp and made it fail silently, which is awesome). Well, ofc, if the user has a working C++ compiler it will build correctly and overwrite the pre-built binary. If you remember node-lws, I didn't have anything else than pre-built binaries and people seemed to go by just fine.

**Comment by silverwind** [comment]
The error doesn't really tell why it failed to build, and It might hide compiler warnings (of which there are many on OS X right now). I also see it problematic that npm is passed a success code without testing if one of the prebuilds actually work. Overall, I still think it's better to error at compile time instead of runtime if functionality can be determined.

**Comment by alexhultman** [comment]
But how is a *reason* why it failed useful for a user who just want to get hacking on his/her/its app? If it failed, it failed. Warnings or not, it's not supposed to be the users responsibility to fix a broken module.

Like, when you buy an Apple product you simply pick it out of a box and start using it, you don't need to open the case and look at what is broken - if something is broken you simply return it and get it fixed. But if you are trying to compile the app on a system which is not compatible and does not have a supported C++11 compiler (gcc 4.7 is not), then I cannot help that unfortunately. The pre-compiled binaries are now statically linked to libstdc++ so they should have even better compatibility with almost all Linux systems.

**Comment by 0x8890** [comment]
>I also get the feeling that most Node.js people absolutely hate C++ more than anything else on earth.

Considering that Node.js is built on top of millions of lines of C++ code, I doubt that is the case ;)

I would like to deploy `uws` on a FreeBSD server, though I haven't tried it yet, and I guess there's no pre-compiled binaries for that. It would be really bad if compilation failed silently, and I don't find out about it until the app starts and I get an error starting Node.js. So I would actually like to know about errors as soon as possible.

**Comment by alexhultman** [comment]
FreeBSD is not supported. This server runs a lot faster on Linux than any other platform.

**Comment by alexhultman** [comment]
This is also kind of the same thing as the other issue: you both have two systems that unfortunately fall outside of the supported range of systems (at this particular time). @silverwind you had problems with a Debian system with GCC 4.7.x while also running some strange musl-libc, and @0x8890 you are talking about FreeBSD.

So yeah, I simply cannot support *all systems in the universe*. If you really want to use uws you should either install a system that will work, or fix the problem yourself. The problems of two users cannot decide how *everyone* should get their module installed. What is the problem of looking in build_log btw?

**Comment by silverwind** [comment]
We should at least document what platforms are currently supported and the exact build requirements (gcc 4.8, make etc). uws on musl looks to work fine, for the record, and I guess BSD could be made compatible (though probably not as fast?) if someone cares.

**Comment by SEAPUNK** [comment]
Opening due to PR imminent. Closed as soon the PR fixing this problem is merged.
