### ISSUE TITLE
Make WebSocket::send defer the onDisconnection callback

### ISSUE THREAD

**Issue by hpohl** [uWebSockets/uWebSockets#335]
Since the commit 29e882841701adf32f189a3ab9b9f1d11b62e809 WebSocket::send may fire the onDisconnection callback. This happens very rarely (about one in a billion times), but causes a crash in my case. I either would have to rewrite a lot or rollback the version and reuse the old API. Is there any other way I can avoid that, maybe by adjusting the uWebSockets source a bit?

FYI, I am the developer of zlap.io and until now everything was running smoothly and I am able to handle 3000 players on a single core with 10 MB/s I/O. Good work :)

**Comment by alexhultman** [comment]
Check this #334 

You can defer whatever you have in onDisconnection yourself. Are you doing this server in C++? Why do you have permessage-deflate enabled? Do you run the latest master? It was stuttering a little bit - do you have NO_DELAY enabled (should be in latest commit). I was able to kill 2 in one round though!

**Comment by alexhultman** [comment]
Ah wait you don't have permessage-deflate, that's good.

**Comment by hpohl** [comment]
Yes, I can defer it myself, but it would still cause a bit of a rewrite. What does NO_DELAY do? I'm using the latest master and I can't see it show up anywhere but in the enum itself.

**Comment by alexhultman** [comment]
This is actually a really good improvement. Currently you cannot broadcast in the disconnection handler because if 1000 clients disconnect at the same time you get 1 disconnection handler called which will call broadcast which will fail for the next socket which will call into the disconnection handler which will broadcast and fail and call into the disconnection handler and eventually lead to stack overflow.

With a deferred disconnection handler you would just leave the socket broken and just return, only to let epoll_wait return with broken pipe error on the next iteration - that's how it should be done really.

**Comment by hpohl** [comment]
So if I got you right, this is going to be fixed in uWebSockets at some point and for now I should just defer it myself, really. What about the NO_DELAY option?

**Comment by alexhultman** [comment]
If you open WebSocket.cpp and search for onEnd and comment out the three first matches from the top then it should defer the disconnection callback to the next iteration. If this works for you, you can PR it because this is needed.

NO_DELAY is a TCP setting that tells the kernel to send packages immediately rather than buffer them up and send many packages together (not what you want in a game). I do set NO_DELAY to true in the very recent commits on master.

**Comment by hpohl** [comment]
Nice, I will try it out and see if the servers still crash. If not, I will create a PR.

**Comment by hpohl** [comment]
Everything working, created PR: https://github.com/uWebSockets/uWebSockets/pull/340
