### ISSUE TITLE
How to graceful shutdown websocket server 

### ISSUE THREAD

**Issue by nepaul** [uWebSockets/uWebSockets#341]
* Operating system we are running
  * Linux
  * OS X
*  platform/language we are using
  * Node.js
* We are not using SSL.

## I try like below, but it not worked.
```
const WebSocket = require('uws').Server;
const wss = new WebSocket({
  port: 3000
});
wss.on('connection', function connection(ws) {
  ws.on('message', function incoming(message) {
    console.log('received: %s', message);
  });

  ws.send('something');
});

process.on('SIGINT', function sigint() {
  console.log('sigint');
  wss.close((error) => {
    console.log(error);
    console.log('close');
  });
});
```

**Comment by alexhultman** [comment]
Wss.close doesn't take a callback in uws

**Comment by nepaul** [comment]
@alexhultman Thanks.

**Comment by nepaul** [comment]
@alexhultman Thanks.
And how to determine to if it success or fail ?

**Comment by alexhultman** [comment]
It doesn't fail, it always suceeds. I could add a callback but that callback would pretty much just be called the next iteration anyways because as soon as you close the server all sockets will get their disconnection callbacks called and then they have 15 seconds to perform a graceful close but that is not part of the application logic so it doesn't have to care about it. Just consider a server close to always work, but it might take some time if you expect the event loop to fall through after it (up to roughly 15 seconds).

**Comment by nepaul** [comment]
Got it! Thanks for your patience! @alexhultman
