### ISSUE TITLE
cannot detect network changes (no FIN packages needs keepalive)

### ISSUE THREAD

**Issue by arpu** [uWebSockets/uWebSockets#394]
* What operating system are you running?
  * Linux
* What platform/language are you using?
  * Node.js
* Are you using SSL, if so, how?
  * SSL via µWS or Node.js
* Can you show me some short code that triggers your issue?

cannot detect network changes  (like mobile to wifi automatic change)
https://github.com/websockets/ws/issues/353

i need to set keepalive?

**Comment by alexhultman** [comment]
You have about three options:

1. Use the TCP-layer keepalive like you mentioned. This is my personal favorite but some say it doesn't work due to how some proxies work - always those proxies making life hard
2. Use the server.startAutoPing(interval) function of uws. This starts an automatic websocket ping/pong match with the clients. Interval is in milliseconds and can be set to 60000 as an example.
3. Implement your own ping/pong match. This is done in all the wrapper projects and is very inefficient in most (all) cases.

**Comment by arpu** [comment]
one more question for 2.
if i use the server.startAutoPing(interval)  i need to use uws js client too right?

**Comment by alexhultman** [comment]
There is no such thing as uws js client. The ping/pong match is standard and works with any browser without any third party lib.
