### ISSUE TITLE
Alternative event loop ?

### ISSUE THREAD

**Issue by jcelerier** [uWebSockets/uWebSockets#436]
Hello,

Is uWebSockets tied to libuv's event loop, or could it be made so that the event loop be chosen by the user of the library ? For instance to use Qt's, boost::asio's, or the C++ Networking TS's `io_service` ? 

Thanks

**Comment by alexhultman** [comment]
The idea is to depend directly on (a very small portion of) libuv (uv_poll_t, uv_async_t, uv_timer_t) so that the library can be used both in stand alone C++ or as an addon in node.js. However I also wanted to have it run ontop of mTCP and other crazy tech so I started this little side project µUV which is a reimplementation of the uv_poll_t, uv_async_t and uv_timer_t directly ontop of Linux epoll. So with this you can actually remove libuv as a dependency and instead link to µUV.

µUV is a lot more lightweight and also faster than libuv but I did not see any interest in it so I stopped maintaining it. It is located in uUV.cpp and uUV.h and is currently not updated but you should be able to implement a similar "backend" ontop of anything. Basically you need to implement those three features of libuv in a substitute library.

**Comment by jcelerier** [comment]
Okay, good to know. Thanks.

**Comment by alexhultman** [comment]
There are now experimental ASIO support as well as raw epoll. New backends can be added very nicely now. Will be in next version :+1:

**Comment by jcelerier** [comment]
nice! this will be interesting to benchmark.

**Comment by alexhultman** [comment]
IKR? But it is not fully complete, just got it working enough to be sure it will be possible. If you look in Asio.h you get the idea
