### ISSUE TITLE
Origin Header

### ISSUE THREAD

**Issue by thedark1337** [uWebSockets/uWebSockets#440]
Using Node 6.9.5 on Linux. Trying to use uws as a client in node.js. 

I have a project I work on for a 3rd party site that requires an origin: "http://domainof3rdpartysite.com" header to allow connections otherwise it fails the connection. 

I was reading through documentation and code but didn't see a way to include custom options such as that header. Is such a thing possible, if not would it be possible to add it?

Thanks, 
           TheDark1337

**Comment by thedark1337** [comment]
Currently for `ws` I do

```js
   var ws = require('ws');
   ws = new WebSocket('wss://somedomain.com:443/socket', {
       origin: 'https://somedomain.com'
   });
```
Which sets the Origin header to that while connecting to the server, and not during the upgrade request 

Is there a way I can do that in js for `uws` ?

**Comment by MakuraYami** [comment]
I was suprised the npm bindings don't support the entire optional argument in the constructor, took me a while to notice this was missing because typescript told me they did: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/uws/index.d.ts#L38

The ClientOptions, and all arguments that you're currently unable to pass according to this would be: 
```
interface IClientOptions {
    protocol?: string;
    agent?: http.Agent;
    headers?: { [key: string]: string };
    protocolVersion?: any;
    host?: string;
    origin?: string;
    pfx?: any;
    key?: any;
    passphrase?: string;
    cert?: any;
    ca?: any[];
    ciphers?: string;
    rejectUnauthorized?: boolean;
}
```

But the `origin` one in particular is one I'd like to see supported asap too.
