### ISSUE TITLE
Work on experimental speedups

### ISSUE THREAD

**Issue by jimmyt857** [uWebSockets/uWebSockets#446]
Awhile back you described writing a toned down version of libuv (which I see is partially implemented) and also trying out mtcp. I'm interested in working on this myself, so before I start I just wanted to know if you had any design/details in mind. For example, should I use function pointers to swap in/out the mtcp calls? i.e uws_connect(), which is either set to ::connect() or mtcp_connect()

Also, I seem to recall another branch which you were using to work on this, does that have more work done than the uUV stuff in the master?

**Comment by alexhultman** [comment]
I'm unemployed, I cannot afford working on ultra low level stuff nobody uses anyways. I wanted to write a complete TCP stack but it's not going to happen. I need to sell some kidneys and suck some d*ck first of all. I would not use function pointers though but hey nobody cares anyways

**Comment by jimmyt857** [comment]
Haha, alright. I'll start submitting PRs on this when I can, possibly as early as this weekend.

**Comment by alexhultman** [comment]
What I would like to see is a TCP stack with no per socket buffers whatsoever. The driver would just call back with the data as it comes in. Imagine having billions of connections to a single Raspberry Pi. It should be possible, source: gut feeling.

**Comment by bigopon** [comment]
> but hey nobody cares anyways

I care but I don't understand why it's not preferred and pretty curious about it. Can I have some enlightenment pls?

**Comment by alexhultman** [comment]
The only reason this project has more than 4 users is because it leeches off of Node.js's massive popularity. Without acting like a parasite to Node.js it would not have taken off. If you start to deviate from Node.js by fixing low level stuff that cannot possibly be used in Node.js itself you lose 99% of the interest since it doesn't apply to Nodesters anymore. In fact, even by hinting about the fact that Node.js has terrible performance leads to loss of interest since it doesn't line up with the made up unicorn chocolate land of those 99%. It is basic PR, not tech.

**Comment by EduardoRFS** [comment]
We love JS(and node), and you are creating a silver bullet for us.

**Comment by daliwali** [comment]
>If you start to deviate from Node.js by fixing low level stuff that cannot possibly be used in Node.js itself you lose 99% of the interest since it doesn't apply to Nodesters anymore. In fact, even by hinting about the fact that Node.js has terrible performance leads to loss of interest since it doesn't line up with the made up unicorn chocolate land of those 99%. It is basic PR, not tech.

I like the idea of being able to write apps in a scripting language (in this case, JS) while having a performant low-level implementation underneath (uWS). It would be awesome to be able to just swap `require('http')` with `require('uws/http')` and get a faster application for free. Compatibility with frameworks is a nice bonus but for me it doesn't matter since most frameworks nullify the performance boosts.
