### ISSUE TITLE
Why all WS connections are uv_poll_t *webSocket are added to the LIST?

### ISSUE THREAD

**Issue by meiry** [uWebSockets/uWebSockets#449]
Include the following information (where applicable):

* What operating system are you running?
  * Windows
* What platform/language are you using?
  * C++
* Are you using SSL, if so, how?
  no ssl
* Can you show me some short code that triggers your issue?

You made  great lib , i try to learn it so i can implement it it in my server 
Going trhow the code i notice you are collection all the uv_pool_t* 's that are connected to the server via this function : 
```
template <bool isServer>
void Group<isServer>::addWebSocket(uv_poll_t *webSocket) {
    if (webSocketHead) {
        uS::SocketData *nextData = (uS::SocketData *) webSocketHead->data;
        nextData->prev = webSocket;
        uS::SocketData *data = (uS::SocketData *) webSocket->data;
        data->next = webSocketHead;
    }
    webSocketHead = webSocket;
}
```
is it necessary ?  
the reason im asking is that i want to make groups of connections my self , in which some of them 
i will like to send back response and some of them i don't .
what is the best  way in my case to do it ?
Thanks!

**Comment by alexhultman** [comment]
It is used for things like broadcast, auto ping and such. Strictly it is not needed if you make sure to track the connections yourself.

**Comment by meiry** [comment]
Thanks allot 
Can you recomand how i disable the group function ?
I saw that in handleFragment you handle the remove from this group list.

or can i keep the group and keep pointers in sub groups for each group of users i want to handle ?

**Comment by alexhultman** [comment]
A websocket will always belong to 1 and only 1 group. If this suits your needs then use the groups that are in the library, otherwise you will need to create your own container to hold them where you want them. You can transfer a websocket from one group to another (this is slow) to implement things like multithreading, multi-protocol, etc.

There is no timeout for client connection to your server. You have to call group.startAutoPing(timeoutMs) to initiate a timer to ping the sockets and disconnect them when they exceed the set timeout.
