### ISSUE TITLE
Node.js: HttpResponse back pressure?

### ISSUE THREAD

**Issue by ronag** [uWebSockets/uWebSockets#481]
How would achieve the usual `res.write` & `res.on('drain', ...)` stream workflow with uws?

e.g.

```js
src.on('data', but => {
  if (!res.write(buf)) {
    src.pause()
  }
})
res.on('drain', () => src.resume())
```

as far as I can se there is no `drain` event not does `write` return a boolean.

**Comment by alexhultman** [comment]
This is not wrapped yet

**Comment by alexhultman** [comment]
Funny side note: most Node.js projects actually doesn't bother with this. Express and Koa both ignore back pressure.

**Comment by ronag** [comment]
I know you don't like the NodeJS event listeners. I don't really mind something like:

```js
src.onData = buf => {
  if (!res.write(buf)) {
    src.pause()
  }
}
res.onDrain = () => src.resume())
```

**Comment by daliwali** [comment]
>Funny side note: most Node.js projects actually doesn't bother with this. Express and Koa both ignore back pressure.

Actually it is because in Node.js core, using `stream.Writable.end` is mutually exclusive with handling back-pressure (the return value of `write` is dropped). If one sets the `highWatermark` to be larger than the response buffer then it is a non-issue.

I can't think of a use case for handling back pressure from a HTTP response, slow client maybe? Could also terminate the connection if it's an abusive client making lots of slow requests that stay open.

**Comment by lpinca** [comment]
> I can't think of a use case for handling back pressure from a HTTP response, slow client maybe?

Yes.

```js
function onReuest(req, res) {
  fs.createReadStream('/path/to/hugeFile').pipe(res);
}
```

and the same from the other direction if your server is slower than the client.

```js
const req = http.request({ method: 'POST', hostname, port, path});
fs.createReadStream('/path/to/hugeFile').pipe(req);
```

And yes this works with Express.

**Comment by daliwali** [comment]
@lpinca sure, but this example is not how most web applications work, rarely is the request or response written as fast as it can be read, streaming apps are the exception rather than the norm.

A common CRUD app will need to query a database, do some things with the data, serialize the response, and finally send the response to the client. By the time the server can start responding, the entire response is already in memory, so handling back pressure is moot in most use cases.

**Comment by lpinca** [comment]
Yes it depends on the app but I wouldn't sat that streaming data is the exception for Node.js apps, quite the opposite imo.

**Comment by alexhultman** [comment]
https://nodejs.org/api/http.html#http_response_end_data_encoding_callback

response.end takes a callback just like any other write or send function. Express does not care to set this callback, I'm pretty certain (otherwise I would have had to implement this to get it working).

There are many big Node.js projects that ignore handling back pressure

**Comment by lpinca** [comment]
@alexhultman AFAIK Express doesn't use the callback because the [response](https://nodejs.org/dist/latest-v7.x/docs/api/http.html#http_class_http_serverresponse) object is a [Writable Stream](https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_implementing_a_writable_stream) so it uses [readable.pipe()](https://nodejs.org/dist/latest-v7.x/docs/api/stream.html#stream_readable_pipe_destination_options) or `readable.pause()` + `writable.on('drain')` when needed.

**Comment by alexhultman** [comment]
It might do in some cases, I know it always calls unpipe but I added warning prints that say when an event is not implemented and any function not available will just thow an exception and neither of this happens so obviously it doesn't care in the tests I done. I tried a full Express app with links and templates and everything and it didn't print any warnings
