### ISSUE TITLE
uHTTP ELIFECYCLE on stream

### ISSUE THREAD

**Issue by flagello** [uWebSockets/uWebSockets#493]
```
System: macOS
Platform: Node.js
Version: v0.13.0
Features: uws.http
```

```
Warning: res.on(finish) is not implemented!
Warning: req.headers usage past request handler is not supported!
Warning: req.headers usage past request handler is not supported!
Warning: req.headers usage past request handler is not supported!
Warning: res.on(unpipe) is not implemented!
Warning: res.on(drain) is not implemented!
Warning: res.on(error) is not implemented!
_stream_readable.js:590
  dest.once('close', onclose);
       ^

TypeError: dest.once is not a function
    at ReadStream.Readable.pipe (_stream_readable.js:590:8)
    at SendStream.stream (/Users/Will/Library/Mobile Documents/com~apple~CloudDocs/Current/Endeavors/next-uws-server/node_modules/send/index.js:746:10)
    at SendStream.send (/Users/Will/Library/Mobile Documents/com~apple~CloudDocs/Current/Endeavors/next-uws-server/node_modules/send/index.js:655:8)
    at onstat (/Users/Will/Library/Mobile Documents/com~apple~CloudDocs/Current/Endeavors/next-uws-server/node_modules/send/index.js:677:10)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

```JavaScript
const { createServer } = require('uws').http
const { parse } = require('url')
const next = require('next')

const dev = process.env.NODE_ENV !== 'production'
const app = next({ dev })
const handle = app.getRequestHandler()

app.prepare()
.then(() => {
  createServer((req, res) => {
    const parsedUrl = parse(req.url, true)
    const { pathname, query } = parsedUrl

    if (pathname === '/a') {
      app.render(req, res, '/b', query)
    } else if (pathname === '/b') {
      app.render(req, res, '/a', query)
    } else {
      handle(req, res, parsedUrl)
    }
  })
  .listen(3000, (err) => {
    if (err) throw err
    console.log('> Ready on http://localhost:3000')
  })
})
```
Adapted from [`next.js/examples/custom-server`](https://github.com/zeit/next.js/tree/master/examples/custom-server) to research https://github.com/zeit/next.js/issues/1214. (It's trying to stream webpack hmr.)

_Feel free to rename the issue. I wasn't quite sure how to name it._

**Comment by alexhultman** [comment]
uws.http is only a very minimal wrapper. Everything redundant is skipped while still having the remaining part be as close to Node.js style as possible. This means:

* no evemt emitters, only the bare minimal you actually need
* cannot access headers past request handler (this is a sign of bad programming anyways)
* no streams, they are redundant when you have send callbacks and on('data')
* otherwise very reduced interface

JavaScript is a scripting language. This means that every abstraction actually cost real runtime cost and this is why the interface needs to be as minimal as possible to not waste away all perf (the addon can be seen as a leaking diesel engine which brute forces performance up even though you lose 50% of all throughput simply by creating:

* a javascript string to hold url (this alone reduces throughput by up to 100k req/sec)
* creating req, res objects
* calling into JS

V8 can be seen as a brick wall which takes away your performance and

**Comment by alexhultman** [comment]
cuts off your sentences

**Comment by alexhultman** [comment]
Basically V8 is like a potato in an exhaust pipe or bleech in your engine. Like the motor anologies?

**Comment by flagello** [comment]
Thanks for the detailed reply @alexhultman! (Sorry for the delay)
