### ISSUE TITLE
GCD (libdispatch) backend?

### ISSUE THREAD

**Issue by snej** [uWebSockets/uWebSockets#528]
A backend based on libdispatch (aka Grand Central Dispatch, GCD) would eliminate the libuv/ASIO dependency on Apple platforms. This would simplify building, reduce the code size, and maybe increase performance a smidge.

Has there been any thought given to this? How difficult would it be to implement? It looks like a 'simple' matter of modifying Backend.h to conditionally include a new header, say GCD.h, which would define classes Loop, Timer, Poll, Async that are source-compatible with the ones defined in Asio.h, Libuv.h, Epoll.h.

_(I'm throwing this out as a generally useful enhancement, but I may end up implementing this and submitting a PR if we end up choosing uWebSockets for a cross-platform project I'm architect of.)_

**Comment by alexhultman** [comment]
I'm in the middle of "merging" a big refactor that will be the base of 0.14.0. 0.13.0 had only libuv so the interface is still changing (mega refactor). With the big refactor it becomes even easier to implement any backend.

If you want lower level you could look at kqueue, this would be portable to FreeBSD also. And it should be as simple as copying the Epoll.h/.cpp and going from there.

The following is the epoll base of sockets in the refactor:

```c++
// 4 bytes
struct Poll {
    struct {
        int fd : 28;
        unsigned int cbIndex : 4;
    } state = {-1, 0};

    Poll(Loop *loop, uv_os_sock_t fd) {
        fcntl(fd, F_SETFL, fcntl(fd, F_GETFL, 0) | O_NONBLOCK);
        state.fd = fd;
        loop->numPolls++;
    }

    bool isClosing() {
        return state.fd == -1;
    }

    uv_os_sock_t getFd() {
        return state.fd;
    }

    void setCb(void (*cb)(Poll *p, int status, int events)) {
        state.cbIndex = cbHead;
        for (int i = 0; i < cbHead; i++) {
            if (callbacks[i] == cb) {
                state.cbIndex = i;
                break;
            }
        }
        if (state.cbIndex == cbHead) {
            callbacks[cbHead++] = cb;
        }
    }

    // what you put in self is what comes in setCb
    void start(Loop *loop, Poll *self, int events) {
        epoll_event event;
        event.events = events;
        event.data.ptr = self;
        epoll_ctl(loop->epfd, EPOLL_CTL_ADD, state.fd, &event);
    }

    void change(Loop *loop, Poll *self, int events) {
        epoll_event event;
        event.events = events;
        event.data.ptr = self;
        epoll_ctl(loop->epfd, EPOLL_CTL_MOD, state.fd, &event);
    }

    void stop(Loop *loop) {
        epoll_event event;
        epoll_ctl(loop->epfd, EPOLL_CTL_DEL, state.fd, &event);
    }

    void close(Loop *loop) {
        state.fd = -1;
        loop->closing.push_back(this);
    }
};
```

**Comment by alexhultman** [comment]
But yes, this should be super easy to do. You can start implementing it for a certain commit and then we can just update it when I'm done.

**Comment by snej** [comment]
Thanks. Looks like the refactor isn't on a branch available from Github, as what you posted doesn't match either master or experimental. But it looks like the master branch is closer; is that the one you'd suggest working from?

**Comment by alexhultman** [comment]
tinymem is the refactor, but this branch is under crazy development right now

**Comment by alexhultman** [comment]
Hmmmmm.. you know I think its best for you to just implement it on master. I'm doing some big fat changes throughout the whole project in tinymem branch and I think it will be easier to just go with master for now. I will need some time to finish this up before I can merge it. It should be similar but a little bit different. You are kind of in a bad situation right now since 0.13.0 is libuv only and 0.14.0 is in heavy development. There is this 0.14.0alpha1 tag that you might be better off with for now.

**Comment by snej** [comment]
OK, good to know. I've uncovered more requirements on my side that make it look like we should do our actual networking in platform-specific code; my x-plat C++ code would just declare an API to send/receive bytes, then parse & generate WebSocket frames. It looks as though your WebSocketProtocol class does exactly that, without dependencies on networking. I'm going to look at prying it loose and welding it into my code (with credit given to you as the original author, of course.)

**Comment by alexhultman** [comment]
The WebSocketProtocol.h is completely free of dependencies and can be used ontop of any networking if you want to only use that part. Well, it does rely on the Networking.h because it relies on those host-to-networking functions but that could (and should) be fixed up.

**Comment by snej** [comment]
Perfect. I've got it working now — a proof of concept WebSocket client implementation in under 1000 LOC including an Objective-C shell to do the socket I/O and HTTP handshake.

**Comment by alexhultman** [comment]
I have this header for handshakes if you want to use: https://github.com/alexhultman/libwshandshake

**Comment by alexhultman** [comment]
Oh wait, you are doing a client *facepalm*

**Comment by snej** [comment]
I'm eventually doing both, though client is higher priority, so I'll bookmark that — thanks.

**Comment by alexhultman** [comment]
I don't quite get what your end goal is. I understand if you want to strip down the *client* and only use the WebSocketProtocol.h here because µWS is not really that minimal for a client (it starts at 600kb and is not really that polished). Also, I get if you don't want to pull in libstdc++ and such.

Server side is a completely different story - here the initial 600kb doesn't matter and it's far more important to scale with the number of connections. This is what µWS was built to do. You cannot just take the WebSocketProtocol.h and reimplement everything else and expect a better result. Sockets are 64 bytes, WebSockets are 112 bytes and if you compare this to projects like lwan they have something like 40-50 bytes sockets (as compared to 64). Point is, this is pretty slim and far better than other projects. I made this project to be a complete solution - it's one complete package, not just a parser.

By only taking the WebSocketProtocol.h and reimplementing everything else you are basically doing everything over again, only this time you don't have any reference to go by (I used WebSocket++, libwebsockets and websockets/ws as reference and they all failed to perform accordingly).

I don't get it really. What kind of missing features are so important that you feel you need to reimplement everything? Why not just PR or report those issues and get them fixed?

**Comment by snej** [comment]
>Server side is a completely different story

Actually it's not in my case. Hint: _P2P_. You're thinking of a server as a something in a data center, I know. But with P2P, every peer is both a client and a server. 

So this project will have devices running the server role that have limited RAM and storage, and where there's an incentive to keep binaries small, but there's no need to scale beyond a few dozen connections at most. (And if you're thinking "iOS devices aren't so limited; they come with 2GB of RAM now", well, that's not true of the Apple Watch.)

**Comment by alexhultman** [comment]
kk but in that case you can really use any implementation and it makes even less sense to reimplement everything (because you won't notice). libwebsockets is more of an embedded small-ROM-footprint implementation that probably fits better in the embedded world. And it is C-only so it doesn't need to pull in the C++ runtime. In any case, I fixed a few parser bugs and changed it a bit so if you use it, please update it.

**Comment by alexhultman** [comment]
"WebSockets" for me is server connected to browsers doing long-held connections, but people use it in all kinds of ways (even in cases where raw TCP would be sufficient). And since it is connected to browsers it automatically rules out any ability to act as a server. Isn't WebRTC more like what you want?
