### ISSUE TITLE
`WebSocket` class silently throws custom events away

### ISSUE THREAD

**Issue by kdex** [uWebSockets/uWebSockets#544]
The [`WebSocket class`](https://github.com/uWebSockets/uWebSockets/blob/b0169cc79e0d1b53ffbab16a4812e0ef709bfa17/nodejs/src/uws.js#L86) acts as if it was an event emitter, but [doesn't handle custom events properly](https://github.com/uWebSockets/uWebSockets/blob/b0169cc79e0d1b53ffbab16a4812e0ef709bfa17/nodejs/src/uws.js#L135-L146). Custom events with `.emit(…)` are thrown away, as only `message`, `close`, `ping` and `pong` are considered.

This makes it hard to use the `WebSocket` class with `extends`, as `this.emit` becomes unreliable.

I've also checked with `ws`; WebSocket clients will respect custom events there.

**Comment by kdex** [comment]
@alexhultman, About the "read the FAQ & README" label: Your [FAQ page](https://github.com/uWebSockets/uWebSockets/wiki/FAQ) is completely empty. This seems like a mistake.

About the node.js README: I realize that it *does* mention the following:
>  webSocket acts like an EventEmitter with one listener per event maximum.

but it doesn't mention anything about how it drops custom events, which this issue was about.

**Comment by alexhultman** [comment]
I must have missed to put that in the issue template, but requests for "real" EventEmitters is something that has been posted many times over with the same general answer: *will never happen*. It must be the 10th time I respond to this now.

* EventEmitters are flawed, bloated and most importantly not needed. The fact that you have the same event handler put to every single websocket is a bad enough idea on its own (especially since most JavaScripters son't understand the difference between a shared function and an inline lambda). EventEmitters are like cherry on top, the pinnacle of bad design.

* The idea of emitting an event based on passed string values as arguments deeply offends me.

* At most, I would accept an interface like ws.onmessage = function, ws.onclose = function because this lines up with how the browser end works and most importantly, is not tied to some Node.js-specific JavaScript object that *cannot even be used from the native end of the addon*.

I have spent *way* too much time on the Node.js addon than what I've spent on the actual native library and it doesn't matter how many more years I pour into the addon -> it will never satisfy everyone. There will always be details that some users will complain about and frankly I don't care what you think.
