### ISSUE TITLE
Epoll info

### ISSUE THREAD

**Issue by ronag** [uWebSockets/uWebSockets#548]
Not sure if relevant but I found it rather interesting...

https://idea.popcount.org/2017-02-20-epoll-is-fundamentally-broken-12/
https://idea.popcount.org/2017-03-20-epoll-is-fundamentally-broken-22/

**Comment by alexhultman** [comment]
Epoll antipropaganda rather. I've had this sent to me many times and every time I go facepalm. µWS has one event-loop per thread and all sockets on one group belong to the same thread. This makes it completely separate from other threads and makes it possible to scale linearly (well, properly linear scaling requires mTCP) since there is no data sharing between threads.
