### ISSUE TITLE
NPM releases < 0.14.1 removed?

### ISSUE THREAD

**Issue by BenV** [uWebSockets/uWebSockets#551]
I went to work on a project which is using version 0.12.0 and noticed that the npm install failed. It appears that all npm packages below version 0.14.1 have been removed from the registry:

```
npm show uws versions
0.14.1
```

https://www.npmjs.com/package/uws is also only showing one version.

The 0.14.1 changelog mentions something about mismatched versions, so I'm wondering if they were removed intentionally or purposefully, or if I'm just missing something obvious. Hopefully the latter. 

Thanks for all the work on this library, it really is great.

**Comment by petemill** [comment]
Confirmed, using 0.13.1 and install fails. I imagine any project which ever ran `npm install --save uws` will not fail its `npm install`. Unless they changed their package.json to accept all 0.x versions, which takes effort to do and isn't likely.

Must have been a mistake somewhere?

**Comment by alexhultman** [comment]
Yes I'm doing a lot of cleaning removing old obnoxious release tags and old (broken) versions on NPM. 0.14.1 is the latest release, there is no other release on NPM anymore (for good reasons, people shouldn't be using old and known-to-be-broken software).

**Comment by petemill** [comment]
@alexhultman Thanks for all your great work by the way! But won't this break all current projects that have a dependency on uws, even ones that are `npm shrinkwrap`ed. Yes it will force **everyone** to use the latest version, but that would be way too disruptive for people who have test procedures for introducing new package versions. 

If uws was on a release > 1, and you published a new minor release, that would be more understandable (but would still break a lot of dependent libraries and projects), as npm would, in a lot of cases, automatically retrieve the latest minor release from npm. But, since 0.14.x is a new, major release (npm considers 0.X all releases to be major), then most people will now just get errors on their CI / build systems / etc.

And this will be more complicated for projects to solve which rely on libraries, which then rely on uws. Even if not shrinkwrapped, because this is a 0.x release, it may as well be, since the same error will be thrown.

**Comment by alexhultman** [comment]
I get the problem and the hilarious part is that this is the same old leftpad bug of NPM all over again. I was expecting to just delete the releases that were not used by anyone, so I started to unpublish releases one by one but NMP never stopped me. So now every package except for 0.14.1 is unpublished. Isn't NPM wonderful?

Anyways, this is good news for people since it will make them update and not stay on "stable" (read: broken & unmaintained) releases.

**Comment by petemill** [comment]
even better would be to publish 0.13.2, 0.12.2 versions etc, which would automatically upgrade the majority of dependent installations, but I get that's probably more work than justify-able. Any thoughts on going to semantic versioning, above v1.0.0?

**Comment by BenV** [comment]
It is not a huge problem for us to upgrade, and we definitely want to be on a stable version. The issue that we are running into is that our AWS auto-scale groups can not currently add new nodes since the NPM packages are missing, which is a typical NPM pain point. 

Since uws is critical to the performance of our server we check for updates and migrate to them fairly frequently, but it does seem like this is going to cause pain for a lot of users of the library, especially when nested dependencies come into play.

I like the solution that @petemill suggested which is to add back the latest point release of the past few versions, which would likely solve the problem for the vast majority of users.

**Comment by unboundfire** [comment]
@petemill Running into the nested dependency problem for this, I'm all for updating to the latest version, but we should give the major packages that use this a chance to update to the latest version.  Republishing the older versions would help so we don't have to have the leftpad incident all over again

**Comment by CharlesWall** [comment]
Please consider that some implementers need to go through static code analysis before updating to new versions. It may be impractical to update immediately and deleting versions like this could prevent builds, deploys, and even prolong outages.

**Comment by alexhultman** [comment]
These removed NPM releases are gone forever, I don't have any kind of backup of those binaries so I cannot republish them and I'm not going to recompile everything that would take ages. This is a bug with NPM, like I said I was expecting to only delete versions no longer in use. If you absolutely want some version back you need to take this up with NPM.

In any case, all version prior to v0.14.1 are known to have various stability issues so it is not recommended stalling with updates.

**Comment by alexhultman** [comment]
@CharlesWall Your static analyzers haven't done a good enough job then because those old versions are broken af :wink:

**Comment by mkozjak** [comment]
...what @CharlesWall said. But aside npm's problems, I've had a problem with your 'actions' of cleaning up old, 'broken' releases before. You used to own and develop a websocket library written purely in node which I considered using in multiple projects. One day you just decided to clear it all up. So I had to switch to something else, which was a pain.

...and we have a deja vu today again. Any ethics problems?

Btw, thanks for the amazing library. :)
