### ISSUE TITLE
Issues with multithreaded echo exemple

### ISSUE THREAD

**Issue by Fatflo** [uWebSockets/uWebSockets#552]
the exemple does not compile, it seems like onConnection, on onMessage... method's first argument should be a pointer instead of object value.
When changed to a pointer it compiles but the cb methods in threads are never called.

**Comment by alexhultman** [comment]
It works here - maybe your listen fails? It does no longer throw exceptions so maybe you simply missed that listen failed? Will update this example at some point.

**Comment by alexhultman** [comment]
I updated the example now

**Comment by Fatflo** [comment]
Thanks for updating, I tried the mew example. On my macOS 10.12.5 machine, std::thread::hardware_concurrency() returns 8, however the listen method in: if (!h.listen(3000, nullptr, uS::ListenOptions::REUSE_PORT)) can only be called once, for all subsequent started threads I get "Failed to listen" error message. So multithreading does not seem to work in my case.

**Comment by Fatflo** [comment]
By the way, the previous multithreaded example works fine now since I updated to 4f2f685590b23b9aa3fb1f318d89be54d3dbb32b

**Comment by alexhultman** [comment]
Ah, you were on an unreleased development commit without proper transfer support. Btw, this new multithreading example only works on Linux as per the comment. Reuse port is high perf but is a Linux extension not available on OS X.

#554 <- this needs to be fixed to allow higher perf of transfer so that non-Linux systems can do efficient multithreading. Or, you could just listen to many ports and have some proxy load balance for you.

**Comment by Fatflo** [comment]
unfortunately listening on many ports is not an option for me currently. However I'm fine now with the initial multithreaded exemple on macOS and perfs are not very important for what I'm doing currently.
One thing I'm trying to figure out now is a way to replace "int t = rand() % THREADS;" in order to avoid choosing a thread which is still processing, is that something possible ?
