### ISSUE TITLE
All previous versions of uws unpublished(?) from npm registry

### ISSUE THREAD

**Issue by spencer-brown** [uWebSockets/uWebSockets#579]
* What platform/language are you using?
  * Node.js
* What version of uws are you using?
  * Release v0.12.0
* What features of µWS are involved in the issue?
  * Server support (WebSocket)
  * Client support (WebSocket)
  * Server support (HTTP)
* How does the issue reproduce?
  * All the time
* Can you show me some short code that triggers your issue or any other important information?
  * `npm info uws version` --> should show that all previously published versions of `uws` are available, but only 0.14.1 is available, which is build-breaking. Previous versions of `uws` that were made available via the npm registry should remain available.

Older versions no longer available:
<img width="219" alt="screen shot 2017-04-14 at 4 35 01 pm" src="https://cloud.githubusercontent.com/assets/5354793/25058608/565ad666-2130-11e7-998f-59039f138465.png">

Example broken build:
<img width="893" alt="screen shot 2017-04-14 at 4 34 40 pm" src="https://cloud.githubusercontent.com/assets/5354793/25058609/565acc70-2130-11e7-8e9e-ec692af8f827.png">

Thanks! :)

**Comment by spencer-brown** [comment]
Looks like this was already covered in previous issues eg https://github.com/uWebSockets/uWebSockets/issues/551. Unfortunate :(.

**Comment by alexhultman** [comment]
Yes it was a combination of NPM bugs (that allows the unpublishes) and me wanting to push users to the latest release (which btw is the only one getting updates). Many users have stopped updating at 0.12 and some are even still on 0.4 and this is not really okay since I recently fixed some long standing issues that technically could be seen as "security issues" aka you could easily get servers to crash with specific input.

So you *could* probably force your way back to 0.12 by hosting that release somewhere else but the idea here is that it should be a simple update (I haven't seen any new issues from people updating to 0.14). So yeah, it shouldn't be "unfortunate" but more like "please update from broken software releases, it's free and compatible and helps the project mature".

**Comment by spencer-brown** [comment]
@alexhultman I love that you're continuing to update `uws` with new and improved versions :).

You may want to consider npm's [`deprecate`](https://docs.npmjs.com/cli/deprecate) for future releases so that you could share the important information you've explained above without unpublishing previous versions.
